### ISSUE TITLE
Not working for IE11 

### ISSUE THREAD

**Issue by shaangidwani** [aichukanov/iguides#1]
Not working for IE11 please fix asap

**Comment by aichukanov** [comment]
Fixed. Check it please.

**Comment by shaangidwani** [comment]
In chrome its working fine but in ie 11 smart guide lines are not working.same isdue  In demo sites too.

**Comment by aichukanov** [comment]
I know, I found the problem. Download new version of smart-guides.js and check it please. Thank you.
https://github.com/aichukanov/smartguides/blob/master/smart-guides.js
Demo site works wrong because of cache, I forgot to update script version.

**Comment by shaangidwani** [comment]
Its working fine
